config/routes.rb
Rails.application.routes.draw do
  mount Shrine.presign_endpoint(:store) => "/presign"

  devise_for :users, path: 'usr', controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  devise_scope :user do
    get 'usr/edit_profile', :to => 'users/registrations#edit_profile'
    put 'usr/update_profile', :to => 'users/registrations#update_profile'
    get 'usr/edit_account', :to => 'users/registrations#edit_account'
    put 'usr/update_account', :to => 'users/registrations#update_account'
  end

  resources :users, only: [:show, :index, :update] do
    collection do
      post "change_avatar"
    end
  end
  get 'load_more_leaders', to: 'users#load_more'
  get 'load_more_artists', to: 'users#load_more_artists'

  post '/rate' => 'rater#create', :as => 'rate'
  get "leaderboard", to: "users#leaderboard"
  get "choose_profile", to: "users#choose_profile"
  get "get_more_credits", to: "users#get_more_credits"
  get "success_signup", to: "users#success_signup"
  get "terms_and_conduct", to: "users#terms_and_conduct"
  delete "cancel_subscription", to: "users#cancel_subscription"
  post "apply_promocode", to: "users#apply_promocode"
  get "home", to: "users#home"
  get "final_cancellation", to: "home#final_cancellation"

  post "report", to: "home#report"

  # user profile settings urls
  get "usr/rewards", to: 'user_profile_settings#rewards'
  get "usr/egg_credits", to: 'user_profile_settings#egg_credits'
  get "usr/headers", to: 'user_profile_settings#headers'
  get "usr/skins", to: 'user_profile_settings#skins'
  get "usr/downloads", to: 'user_profile_settings#downloads'
  get "usr/billing_order_history", to: 'user_profile_settings#billing_order_history'
  get "usr/friends", to: 'user_profile_settings#friends'
  get "usr/artists", to: 'user_profile_settings#artists'
  get "usr/releases", to: 'user_profile_settings#releases'
  get "usr/chirp_feeds", to: 'user_profile_settings#chirp_feeds'
  get "usr/notifications", to: 'user_profile_settings#notifications'
  get "usr/cancel_account", to: 'user_profile_settings#cancel_account'
  put "usr/update_notification_settings", to: 'user_profile_settings#update_notification_settings', :as => 'update_notification_settings'
  put "usr/update_user_header", to: 'user_profile_settings#update_user_header', :as => 'update_user_header'
  delete "usr/cancel_account", to: 'user_profile_settings#cancel_account_perform'

  get "get_feed_token", to: "feeds#get_feed_token"
  get "add_feed_item", to: "feeds#add_feed_item"
  get "add_notify_item", to: "feeds#add_notify_item"
  get "load_more_feed", to: "feeds#load_more"
  get "is_seen", to: "feeds#is_seen"
  get "is_read", to: "feeds#is_read"

  get "chirp_feed", to: "users#chirp_feed"
  get "release_feed", to: "users#release_feed"
  get "artists_feed", to: "users#artists_feed"
  get "friends_feed", to: "users#friends_feed"
  get "announcement_feed", to: "users#announcement_feed"
  get "interviews_feed/:id", to: "users#interviews_feed", as: "interviews_feed"
  get "videos_feed/:id", to: "users#videos_feed", as: "videos_feed"
  get "others_feed/:id", to: "users#others_feed", as: "others_feed"
  get "friends/:id", to: "users#friends", as: "friends"
  get "idols/:id", to: "users#idols", as: "idols"

  ActiveAdmin.routes(self)

  devise_scope :user do
    authenticated do
      root 'users#home', as: :authenticated_root
    end
  end

  get 'admins/:id', to: 'users#admin', as: 'admin'
  get 'artists/:id', to: 'users#artist', as: 'artist'
  get 'artist_releases/:id', to: 'users#artist_releases', as: 'artist_releases'
  get 'artist_tracks/:id', to: 'users#artist_tracks', as: 'artist_tracks'
  get 'artists', to: 'users#artists'
  get 'badges/:id', to: 'users#badges', as: 'badges'

  get 'about', to: 'home#about'
  get 'birdfeed', to: 'home#birdfeed'
  post 'share', to: 'home#share'
  get 'badge-notify', to: 'home#badge_notify'
  get 'pricing', to: 'home#pricing'
  get 'information', to: 'home#information'
  get 'how_eggs_work', to: 'home#how_eggs_work'

  resources :contacts, only: [:index, :create]
  resources :slider_images

  resources :announcements, only: [:show]
  resources :releases, only: [:show, :index]
  get '/releases/:id/download', to: 'releases#download', as: :release_download
  get '/tracks/:id/download', to: 'tracks#download', as: :track_download
  get "search_releases", to: "releases#search"
  get "fill_track_title", to: "tracks#fill_track_title"
  get 'load_more_releases', to: 'releases#load_more'

  resources :tracks
  get 'track_listened', to: 'tracks#track_listened'
  get 'track_listened_for_review', to: 'tracks#track_listened_for_review'
  get 'tracks_play', to: 'tracks#play'
  get 'tracks_list', to: 'tracks#list'
  get 'track_clicked', to: 'tracks#track_clicked'

  resources :player do
    get 'liked_playlists'
    get 'liked_tracks'
    get 'recently_tracks'
    get 'downloaded_tracks'
    get 'favorites'
    get 'connect'
    get 'listen'
    get 'artists'
    get 'fans'
    get 'playlists'
    get 'badges'
  end
  get 'player_load_more_leaders', to: 'player#load_more_fans'
  get 'player_load_more_artists', to: 'player#load_more_artists'

  resources :playlists
  get 'playlist_load', to: "playlists#load"
  post "sync_playlist", to: "playlists#sync_playlist"

  namespace :callbacks do
    post 'transloadit', to: 'transloadit#create'
    post 'braintree/nonce', to: 'braintree#nonce'
    # post 'braintree/analytics_notify', to: 'braintree#analytics_notify'
  end


  resources :topics
  resources :posts

  resources :follows
  get '/accept_request/:user_id/', to: 'follows#accept_request', as: :accept_request
  get '/reject_request/:user_id/', to: 'follows#reject_request', as: :reject_request
  get 'is_seen_requests', to: 'follows#is_seen_requests'


  resources :comments
  get 'comment_reply_form', to: 'comments#reply_form'

  resources :likes

  resources :chirp, controller: 'topic_categories', only: [:show, :index] do
    # get 'category/:id', to: "topics#category"
    resources :topics
    # get 'pin'
    # get 'unpin'
    # get 'lock'
    # get 'unlock'
  end

  resources :notifications

  root "home#index"

  mount Shrine.presign_endpoint(:store) => "/presign"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  # belongs_to :user, optional: true
  belongs_to :admin, optional: true, foreign_key: "admin_id", class_name: "User"
  belongs_to :release, optional: true
  has_many :likes, as: :likeable
  has_many :comments, as: :commentable


  # after_save :change_published_date, only: :update
  after_create :add_to_general_feed
  after_destroy :remove_from_general_feed

  mount_uploader :avatar, ReleaseUploader

  include StreamRails::Activity
  # as_activity

  def followers
    User.joins(:follows).where("follows.followable_id = ? AND follows.followable_type = 'Announcement'", self.id)
  end

  private

    def add_to_general_feed
      announcement_create_feed = StreamRails.feed_manager.get_feed( 'announcement_create', 1 )
      masterfeed = StreamRails.feed_manager.get_feed( 'masterfeed', 1 )

      activity = {
        actor: "User:#{User.with_role(:admin).first.id}",
        verb: "Release",
        object: "Announcement:#{self.id}",
        foreign_id: "Announcement:#{self.id}",
        time: DateTime.now.iso8601
      }

      announcement_create_feed.add_activity(activity)
      masterfeed.add_activity(activity)
      # User.all.each do |u|
      #   user_feed = StreamRails.feed_manager.get_user_feed(u.id)
      #   user_feed.add_activity(activity)
      # end
    end

    def remove_from_general_feed
      feed = StreamRails.feed_manager.get_feed( 'announcement_create', 1 )
      feed.remove_activity("Announcement:#{self.id}", foreign_id=true)
    end

    # def change_published_date
    #   if published_at_changed?
    #     feed = StreamRails.feed_manager.get_feed( 'general_actions', 1 )
    #     feed.remove_activity("Announcement:#{self.id}", foreign_id=true)

    #     activity = create_activity

    #     feed.add_activity(activity)
    #   end
    # end
end

app/views/announcements/show.html.erb
<div class="release-present">
  <%= image_tag(@announcement.avatar.url, class: "release-avatar left-avatar") %>
  
  <div class="release-bgrd bg-green">
    <%#= image_tag 'dj.jpg' %>

    <div class="release-header">
      <div class="release-exclusive">
        <%= image_tag 'icons/user-logo-icon.svg' %>
        <div>ONLY ON<br>
        BIRDFEED</div>
      </div>

      <div class="release-likes">
        <%= render partial: 'likes/like_button', locals: { object: @announcement,  style: 'release' } %>
      </div>

      <%= render partial: 'layouts/share', locals: { object: @announcement, icon: 'white' } %>
    </div>
  </div>
</div>

<div class="release-info mb-4">
  <h1 class="fz-23 mb-4"><%= @announcement.title.upcase %></h1>

  <div class="truncated-description">
    <% if @announcement.text.present? %>
      <article><%= strip_tags(@announcement.text).gsub('&amp;','&').truncate(400) %></article>

      <% if @announcement.text.html_safe.truncate(400) != @announcement.text.html_safe %>
        <a href="#" class="truncated-long">Read more</a>
      <% end %>

      <article><%= @announcement.text.html_safe %></article>
      <a href="#" class="truncated-short"><br><br>Read less</a>
    <% end %>
  </div>

  
  <%#= link_to "Q&A", chirp_path, class: "btn c-btn-transparent btn-wide" %>
</div>

<div class="row">
  <div class="col-md-8">

    <div class="c-panel bg-white">
      <div class="c-flag mb-4">ANNOUNCEMENT FEED</div>

      <%# if current_user && @announcement.user_id == current_user.id %>
        <button class="btn c-btn-blue mt-1 btn-wide" type="button" data-toggle="modal" data-target="#addcommentModal">
          POST A COMMENT
        </button>
      <%# end %>

      <%= render partial: 'follows/follow_button', 
          locals: { object: @announcement, 
                    opt: { 
                        classes: "btn btn-wide follow-button-black",
                        text: ['follow this feed', 'unfollow this feed'] } } %>

      <div class="feed-block light-scroll" data-feed-id="<%= @announcement.id %>" data-feed="announcement">
        <%= render 'feeds/commentable_feed' %>
      </div>

      <div id="loading" style="display: none;">Loading...</div>
      
    </div>
  </div>

  <div class="col-md-4">
    <div class="sticky-top">
      <!-- FOLLOWERS -->
      <div class="c-panel bg-white mb-4">
        <div class="c-flag c-flag-inner mb-2">FEED FOLLOWERS</div>

        <div>
          <% @announcement.followers.each do |user| %>
            <%= link_to user, class: "d-inline-block mr-2 mb-2" do %>
              <%= image_tag user.avatar.thumb, class: "user-avatar", alt: '' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if current_user %>
  <% content_for :body_area do %>
    <div class="modal modal-blured" id="addcommentModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-dialog-wide" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body w-100">
            <h5 class="modal-title">Add your comment</h5>

            <%= form_for current_user.comments.build, 
              html: { class: "feed-form w-75" }, remote: true do |f| %>
              <%= f.hidden_field :commentable_type, value: "Announcement" %>
              <%= f.hidden_field :commentable_id, value: @announcement.id %>
              <%= f.label :body, class: "sr-only" %>
              <%= f.text_area :body, rows: 10, placeholder: "Type text", 
                  max: 200, class: "emoji-area" %>
              <%= f.submit "ADD TO FEED", class: "btn c-btn-blue btn-wide" %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>