config/routes.rb
Rails.application.routes.draw do
  mount Shrine.presign_endpoint(:store) => "/presign"

  devise_for :users, path: 'usr', controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  devise_scope :user do
    get 'usr/edit_profile', :to => 'users/registrations#edit_profile'
    put 'usr/update_profile', :to => 'users/registrations#update_profile'
    get 'usr/edit_account', :to => 'users/registrations#edit_account'
    put 'usr/update_account', :to => 'users/registrations#update_account'
  end

  resources :users, only: [:show, :index, :update] do
    collection do
      post "change_avatar"
    end
  end
  get 'load_more_leaders', to: 'users#load_more'
  get 'load_more_artists', to: 'users#load_more_artists'

  post '/rate' => 'rater#create', :as => 'rate'
  get "leaderboard", to: "users#leaderboard"
  get "choose_profile", to: "users#choose_profile"
  get "get_more_credits", to: "users#get_more_credits"
  get "success_signup", to: "users#success_signup"
  get "terms_and_conduct", to: "users#terms_and_conduct"
  delete "cancel_subscription", to: "users#cancel_subscription"
  post "apply_promocode", to: "users#apply_promocode"
  get "home", to: "users#home"
  get "final_cancellation", to: "home#final_cancellation"

  post "report", to: "home#report"

  # user profile settings urls
  get "usr/rewards", to: 'user_profile_settings#rewards'
  get "usr/egg_credits", to: 'user_profile_settings#egg_credits'
  get "usr/headers", to: 'user_profile_settings#headers'
  get "usr/skins", to: 'user_profile_settings#skins'
  get "usr/downloads", to: 'user_profile_settings#downloads'
  get "usr/billing_order_history", to: 'user_profile_settings#billing_order_history'
  get "usr/friends", to: 'user_profile_settings#friends'
  get "usr/artists", to: 'user_profile_settings#artists'
  get "usr/releases", to: 'user_profile_settings#releases'
  get "usr/chirp_feeds", to: 'user_profile_settings#chirp_feeds'
  get "usr/notifications", to: 'user_profile_settings#notifications'
  get "usr/cancel_account", to: 'user_profile_settings#cancel_account'
  put "usr/update_notification_settings", to: 'user_profile_settings#update_notification_settings', :as => 'update_notification_settings'
  put "usr/update_user_header", to: 'user_profile_settings#update_user_header', :as => 'update_user_header'
  delete "usr/cancel_account", to: 'user_profile_settings#cancel_account_perform'

  get "get_feed_token", to: "feeds#get_feed_token"
  get "add_feed_item", to: "feeds#add_feed_item"
  get "add_notify_item", to: "feeds#add_notify_item"
  get "load_more_feed", to: "feeds#load_more"
  get "is_seen", to: "feeds#is_seen"
  get "is_read", to: "feeds#is_read"

  get "chirp_feed", to: "users#chirp_feed"
  get "release_feed", to: "users#release_feed"
  get "artists_feed", to: "users#artists_feed"
  get "friends_feed", to: "users#friends_feed"
  get "announcement_feed", to: "users#announcement_feed"
  get "interviews_feed/:id", to: "users#interviews_feed", as: "interviews_feed"
  get "videos_feed/:id", to: "users#videos_feed", as: "videos_feed"
  get "others_feed/:id", to: "users#others_feed", as: "others_feed"
  get "friends/:id", to: "users#friends", as: "friends"
  get "idols/:id", to: "users#idols", as: "idols"

  ActiveAdmin.routes(self)

  devise_scope :user do
    authenticated do
      root 'users#home', as: :authenticated_root
    end
  end

  get 'admins/:id', to: 'users#admin', as: 'admin'
  get 'artists/:id', to: 'users#artist', as: 'artist'
  get 'artist_releases/:id', to: 'users#artist_releases', as: 'artist_releases'
  get 'artist_tracks/:id', to: 'users#artist_tracks', as: 'artist_tracks'
  get 'artists', to: 'users#artists'
  get 'badges/:id', to: 'users#badges', as: 'badges'

  get 'about', to: 'home#about'
  get 'birdfeed', to: 'home#birdfeed'
  post 'share', to: 'home#share'
  get 'badge-notify', to: 'home#badge_notify'
  get 'pricing', to: 'home#pricing'
  get 'information', to: 'home#information'
  get 'how_eggs_work', to: 'home#how_eggs_work'

  resources :contacts, only: [:index, :create]
  resources :slider_images

  resources :announcements, only: [:show]
  resources :releases, only: [:show, :index]
  get '/releases/:id/download', to: 'releases#download', as: :release_download
  get '/tracks/:id/download', to: 'tracks#download', as: :track_download
  get "search_releases", to: "releases#search"
  get "fill_track_title", to: "tracks#fill_track_title"
  get 'load_more_releases', to: 'releases#load_more'

  resources :tracks
  get 'track_listened', to: 'tracks#track_listened'
  get 'track_listened_for_review', to: 'tracks#track_listened_for_review'
  get 'tracks_play', to: 'tracks#play'
  get 'tracks_list', to: 'tracks#list'
  get 'track_clicked', to: 'tracks#track_clicked'

  resources :player do
    get 'liked_playlists'
    get 'liked_tracks'
    get 'recently_tracks'
    get 'downloaded_tracks'
    get 'favorites'
    get 'connect'
    get 'listen'
    get 'artists'
    get 'fans'
    get 'playlists'
    get 'badges'
  end
  get 'player_load_more_leaders', to: 'player#load_more_fans'
  get 'player_load_more_artists', to: 'player#load_more_artists'

  resources :playlists
  get 'playlist_load', to: "playlists#load"
  post "sync_playlist", to: "playlists#sync_playlist"

  namespace :callbacks do
    post 'transloadit', to: 'transloadit#create'
    post 'braintree/nonce', to: 'braintree#nonce'
    # post 'braintree/analytics_notify', to: 'braintree#analytics_notify'
  end


  resources :topics
  resources :posts

  resources :follows
  get '/accept_request/:user_id/', to: 'follows#accept_request', as: :accept_request
  get '/reject_request/:user_id/', to: 'follows#reject_request', as: :reject_request
  get 'is_seen_requests', to: 'follows#is_seen_requests'


  resources :comments
  get 'comment_reply_form', to: 'comments#reply_form'

  resources :likes

  resources :chirp, controller: 'topic_categories', only: [:show, :index] do
    # get 'category/:id', to: "topics#category"
    resources :topics
    # get 'pin'
    # get 'unpin'
    # get 'lock'
    # get 'unlock'
  end

  resources :notifications

  root "home#index"

  mount Shrine.presign_endpoint(:store) => "/presign"
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  include ApplicationHelper
  include UsersHelper
  
  before_action :set_vars
  before_action :set_notifications, 
      only: [:liked_tracks, :recently_tracks, :downloaded_tracks, :favorites,
        :liked_playlists, :connect, :listen, :artists, :playlists, :fans, :badges]
  
  def liked_tracks
    @tracks = @user.liked_by_type('Track').map do |_track|
      TrackPresenter.new(_track, current_user, @browser)
    end

    @tracks.compact!
  end

  def recently_tracks
    @with_index = true
    @tracks = @user.recently_items.map do |item|
      TrackPresenter.new(item.track, current_user, @browser) if item.track
    end

    @tracks.compact!
  end

  def downloaded_tracks
    @tracks = @user.downloads.map do |d| 
      TrackPresenter.new(d.track, current_user, @browser) if d.track
    end

    @tracks.compact!
  end

  def favorites
    @playlists = @user.liked_by_type('Playlist').limit(3)

    @tracks = @user.liked_by_type('Track').limit(7).map do |_track|
      TrackPresenter.new(_track, current_user, @browser)
    end

    @releases = @user.liked_by_type('Release').limit(3).map do |_release|
      ReleasePresenter.new(_release, current_user)
    end

    @tracks.compact!
    @releases.compact!
  end

  def liked_playlists
    @playlists = @user.liked_by_type('Playlist')
  end

  def connect
    if get_setting('main-area-promo')
      @main_area = { link: get_setting('main-area-promo'), 
                     img: get_setting_res('main-area-promo')}
    else
      @main_area = nil
    end
  end

  def listen
    @top_releases = Release.published.order(created_at: :desc).limit(3)
    top_tracks_ids = 
      RecentlyItem.group(:track_id)
                  .count
                  .sort_by {|k,v| v}
                  .reverse[0..4]
                  .map {|a| a[0]}
    @top_tracks = top_tracks_ids.map { |id| Track.find_by_id id }.compact
    @top_playlists = Playlist.all.order(created_at: :desc).limit(3)
  end

  def artists
    @artists = leaderboard_query(User.with_role(:artist), params[:page] || 1, 30, true)
  end

  def load_more_artists
    @artists = leaderboard_query(User.with_role(:artist), params[:page], 30, false)
  end

  def fans
    @users = leaderboard_query('leaders', params[:page] || 1, 30, true)
  end

  def load_more_fans
    @users = leaderboard_query('leaders', params[:page], 30, false)
  end

  def playlists
    @playlists = Playlist.order(created_at: :desc).limit(20)
  end

  def badges
    @membership = @user.badges
                       .joins(:badge_kind)
                       .where( badge_kinds: {ident:'membership_level'} )
    @general_badges = {}
    %w(music forum community).each do |ident|
      @general_badges[ident] = @user.badges
                         .joins(:badge_kind)
                         .where( badge_kinds: {ident: ident} )
    end
    @points = {
      listen: @user.points(BadgeKind.find_by_ident('music').try(:id)),
      connect: @user.points(BadgeKind.find_by_ident('forum').try(:id)),
      play: @user.points(BadgeKind.find_by_ident('community').try(:id))
    }

    @progress = {
      listen: @user.next_badges[BadgeKind.find_by_ident('music').try(:id)],
      connect: @user.next_badges[BadgeKind.find_by_ident('forum').try(:id)],
      play: @user.next_badges[BadgeKind.find_by_ident('community').try(:id)]
    }
  end

  private

    def set_vars
      @user = User.find params[:player_id]
    end

end

app/views/player/_badges_content.html.erb
<div class="bg-white p-4">
  <div class="d-flex justify-content-between">
    <h2 class="h2-big">U.G Merit</h2>
    <h2 class="h2-big">FAM Status #<%= user_position(@user) %></h2>
  </div>

  <div class="d-flex justify-content-between my-4">
    <% for badge in @membership %>
      <div class="fan-badge">
          <%= image_tag badge.image if badge.image.present? %>
          <p class="text-center subheader"><%= badge.name %></p>
      </div>
    <% end %>

    <% (5 - @membership.count).times do |i| %>
      <div class="fan-badge">
        <%= image_tag 'icons/empty_badge.png' %>
      </div>
    <% end %>
  </div>
</div>


<div class="d-flex justify-content-between p-4">
  <h2 class="h2-big">U.G Merit</h2>
  <h2 class="h2-big">
    <%= number_with_delimiter(@user.points, :delimiter => ',') %> pts
  </h2>
</div>

<div class="bg-dark d-flex p-4">
  <% @points.each do |kind, points| %>
    <div class="badges-points">
      <h2 class="h2-big text-white d-block mb-4">
        <%= number_with_delimiter(points, :delimiter => ',') %>
      </h2>
      <h2 class="text-c-<%= kind %>"><%= kind %></h2>
    </div>
  <% end %>
</div>

<div class="bg-white p-4">
  <div class="rating-chart d-flex flex-wrap">
    <div class="rating-kinds text-right pt-2 mt-4">
      <% @progress.each do |kind, percents| %>
        <div class="subheader mb-4"><%= kind %></div>
      <% end %>
    </div>
    <div class="rating-bars flex-grow-1 px-3 mt-4">
      <% @progress.each do |kind, percents| %>
        <% color = case kind
          when :listen then "red"
          when :connect then "blue"
          when :play then "yellow"
          end %>
        <div class="progress-wrapper w-100">
          <div class="progress-<%= color %> mb-3" style="height: 26px;">
            <div class="c-progress-bar" 
                 role="progressbar" 
                 style="width: <%= percents || 0 %>%" 
                 aria-valuenow="75" 
                 aria-valuemin="0" 
                 aria-valuemax="100"></div>
          </div>
        </div>
      <% end %>
    </div>
    <%= image_tag 'icons/Achievement-1.png' %>
  </div>
</div>

<div class="p-4">
  <h2 class="my-4">Level 1 U.G Merit Collect</h2>

  <div class="d-flex justify-content-between flex-wrap pr-4 mb-4">
    <div>
      <%= image_tag 'icons/birdfeed-header.png' %>
      <div class="text-center subheader mt-2">INitiation Badge</div>
    </div>

    <div>
      <%= image_tag 'icons/listen.png' %>
      <div class="text-center subheader mt-2">Listen</div>
    </div>

    <div>
      <%= image_tag 'icons/connect.png' %>
      <div class="text-center subheader mt-2">Connect</div>
    </div>

    <div>
      <%= image_tag 'icons/play_2.png' %>
      <div class="text-center subheader mt-2">Play</div>
    </div>
  </div>

  <% @general_badges.each do |ident, badges| %>
    <h2 class="d-block"><%= ident %></h2>
    <div class="d-flex justify-content-between flex-wrap mb-4">

      <% badges.each do |badge| %>
        <div class="fan-badge">
            <%= image_tag badge.image, style: "width: 70px; height: 77px;" if badge.image.present? %>
            <p><%= badge.name %></p>
        </div>
      <% end %>

      <% (10 - badges.count).times do |i| %>
        <%= image_tag 'icons/empty_badge.png', style: "width: 70px; height: 77px;" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/player/_favorites_content.html.erb
<h2>Favorited Playlists</h2>
<%= link_to 'see all', player_liked_playlists_path(user), class: 'see-all' %>
<%= render partial: 'playlists/list', locals: { playlists: playlists } %>

<h2 class="mt-4">Favorited  TRACKS</h2>
<%= link_to 'see all', player_liked_tracks_path(user), class: 'see-all' %>
<%= render partial: 'playlists/playlist_items', 
    locals: { tracks: tracks, source_type: 'liked', source_id: user.id } %>

<h2 class="mt-4">Favorited Releases</h2>
<%= link_to "see all", 
    releases_path(
      filters: { liked: true }, 
      player: true, 
      user_id: user.id),
      class: "see-all" %>
<div class="row mt-3 releases-list">
  <% for release in releases %>
    <div class="col-lg-4 col-md-6 mb-5">
      <%= render(release) %>
    </div>
  <% end %>
</div>

app/views/player/_last_release_banner.html.erb
<% release = ReleasePresenter.new(Release.published.first, current_user) %>
<div class="listen-banner">
  <% if release.showcase.present? %>
    <%= image_tag release.showcase.url, class: "banner-img" %>
  <% else %>
    <%= image_tag release.avatar.url(:large), class: "banner-img" %>
  <% end %>

  <%= link_to '', "#",
              data: {
                source_type: 'release',
                source_id: release.id,
                virtual: false
              },
              class: "play-release-#{release.id} playlist-play-playlist",
              remote: true %>

  <div class="banner-footer">
    <div class="time"><%= time_ago_in_words( release.release_date ).upcase %> AGO</div>

    <div class="left-side">
      <div class="banner-title">
        <%= release.title %>
        <span class="tracks-count"><%= "#{release.tracks.count} #{'track'.pluralize(release.tracks.count)}" %></span>
        <div class="release-artists">
          By <%= release.artists(2) %>
        </div>
      </div>

      <%#= release.average('main').try(:avg).try(:round,1) %>
      <%= rating_for release, 'main',
          star: 4,
          cancel: false,
          readonly: true,
          star_on: image_path('rate/egg/star-on.svg'),
          star_half: image_path('rate/egg/star-on.svg'),
          star_off: image_path('rate/egg/star-off.svg')
        %>
    </div>

    <%= link_to 'Details', release, class: 'details' %>
  </div>
</div>

app/views/player/_player_page_menu.html.erb
<% if defined?(@user) %>
  <div class="playlist-nav">
    <div class="playlist-nav-body">
      <ul>
        <li class="mt-2 mb-4 nav-bar">
          <%= image_tag 'icons/icon-chevron-black.svg', 
              style: 'cursor: pointer; margin-right: 30px;', 
              onclick: "window.history.back();" %>
          <%= image_tag 'icons/icon-chevron-black.svg', 
              style: 'cursor: pointer; transform: rotate(180deg);', 
              onclick: "window.history.forward();" %>
        </li>
        <li class="playlist-nav-subheader">Music&nbsp;</li>
        <li class="<%= 'active' if current_page?("/releases?player=true&user_id=#{@user.id}") %>">
          <%= link_to "All Releases", 
                      releases_path(
                        player: true, user_id: @user.id,
                        page: session[:page_on_player] ? session[:page_on_player][0] : nil),
                      id: "playlist-all-releases", remote: true %>
        </li>        
        <li class="<%= 'active' if current_page?("/releases?filters[release_type]=2&player=true&user_id=#{@user.id}") %>">
          <%= link_to "Dirtybird", 
              releases_path(
                filters: { release_type: 2 }, 
                player: true,
                user_id: @user.id,
                page: session[:page_on_player] ? session[:page_on_player][2] : nil),
              id: "playlist-select-releases", remote: true %>
        </li>
        <li class="<%= 'active' if current_page?("/releases?filters[release_type]=1&player=true&user_id=#{@user.id}") %>">
          <%= link_to "Birdfeed Exclusive", 
              releases_path(
                filters: { release_type: 1 }, 
                player: true,
                user_id: @user.id,
                page: session[:page_on_player] ? session[:page_on_player][0] : nil),
              id: "playlist-exclusive-releases", remote: true %>
        </li>
        <li class="playlist-nav-subheader">Library&nbsp;</li>
        <% if current_user %>
          <li class="<%= 'active' if current_page?(player_badges_path(current_user)) %>">
            <%= link_to "Badges", player_badges_path(current_user), id: "playlist-badges", remote: true %>
          </li>
          <li class="<%= 'active' if current_page?(playlists_path(user_id: current_user.id)) %>">
            <%= link_to "Playlists", playlists_path(user_id: current_user.id), 
                id: "playlist-user", remote: true %>
          </li>
          <li class="<%= 'active' if current_page?(player_favorites_path(current_user)) %>">
            <%= link_to 'favorites', player_favorites_path(current_user), id: "playlist-favorites", remote: true %>
          </li>
          <li class="<%= 'active' if current_page?(player_recently_tracks_path(current_user)) %>">
            <%= link_to "Recently Played", player_recently_tracks_path(current_user),
                id: "playlist-favorited-tracks", remote: true %>
          </li>
          <li class="<%= 'active' if current_page?(player_downloaded_tracks_path(current_user)) %>">
            <%= link_to "Downloads", player_downloaded_tracks_path(current_user),
                id: "playlist-favorited-downloads", remote: true %>
          </li>
        <% end %>
<!--         <li class="playlist-nav-subheader">Playlists&nbsp;</li>
        <%# for playlist in @playlists %>
          <li class="<%#= 'active' if current_page?(playlist_path(playlist)) %>">
            <%#= link_to playlist.name, playlist,
                id: "playlist-#{playlist.id}" %>
          </li>
        <%# end %> -->
      </ul>
    </div>
  </div>
<% end %>

app/views/player/badges.js.erb
$('.playlist-nav-body li.active').removeClass('active')
$('#playlist-badges').parent().addClass('active');

$('.music-wrapper').empty();

$('.music-wrapper').append(`<%= escape_javascript(render partial: 'badges_content') %>`);

app/views/player/connect.html.erb
<% content_for :user_header_title do %>
  <%= image_tag 'icons/bird-blue.svg' %>
  Connect
<% end %>

<% if @user.has_role? :artist %>
  <%= render 'users/artist_header' %>
<% else %>
  <%= render 'users/user_header' %>
<% end %>

<div class="row">
  <div class="col-lg-3">
    <%= render 'player/player_page_menu' %>
  </div>

  <div class="col-lg-9 music-wrapper">
    <div class="music-block player-main-area" style="padding-top: 280px;">
      <% if @main_area %>
      <a href="<%= @main_area[:link] %>" class="listen-banner">
        <%= image_tag @main_area[:img], class: "banner-img" %>
      </a>
      <% else %>
        <%= render 'last_release_banner' %>
      <% end %>

      <div class="main-area-nav mb-3">
        <div class="row h-100">
          <div class="col-md-4 d-flex align-items-center justify-content-center">
            <%= link_to player_artists_path(current_user || @user) do %>
              <%= image_tag 'dirtybird-bbq-stage.jpg', class: 'main-area-nav-bgrd' %>
              <span class="main-area-nav-caption">Artists</span>
            <% end %>
          </div>

          <div class="col-md-4 d-flex align-items-center justify-content-center">
            <%= link_to player_fans_path(current_user || @user) do %>
              <%= image_tag 'dirtybird_bbq.jpg', class: 'main-area-nav-bgrd' %>
              <span class="main-area-nav-caption">Community</span>
            <% end %>
          </div>

          <div class="col-md-4 d-flex align-items-center justify-content-center">
            <%= link_to friends_path(current_user || @user) do %>
              <%= image_tag 'JLB.jpg', class: 'main-area-nav-bgrd' %>
              <span class="main-area-nav-caption">Friends</span>
            <% end %>
          </div>
        </div>
      </div>

      <h2>Latest Artists</h2>
      <%= link_to 'All Artists', artists_path, class: 'see-all' %>
      <hr class="mt-1">

      <div class="row">
        <% User.with_role(:artist).order(created_at: :desc).limit(4).each do |user| %>
          <div class="col-md-6 mb-3">
            <%= render 'users/artist_gray', object: user %>
          </div>
        <% end %>
      </div>

      <h2 class="mt-4">Latest Birds</h2>
      <%= link_to 'All Members', leaderboard_path, class: 'see-all' %>
      <hr class="mt-1">

      <div class="row mb-4">
        <% User.where("users.id NOT IN (?)", 
              User.with_role(:artist).pluck(:id) + User.with_role(:admin).pluck(:id))
                .order(created_at: :desc)
                .limit(4).each do |user| %>
          <div class="col-md-6 mb-3">
            <%= render 'users/user_gray', object: user %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">
  activePlaylist = "<%= params[:active_playlist] %>";

  switch (activePlaylist) {
    case 'All Releases':
      $('a#playlist-all-releases').click();
      break;
    
    case 'Dirtybird':
      $('a#playlist-select-releases').click();
      break;
    
    case 'Birdfeed Exclusive':
      $('a#playlist-exclusive-releases').click();
      break;
  
    default:
      $('a#playlist-all-releases').click();
      break;
  }
  
  if (activePlaylist == '') {
    
  }

  $(window).on('load', function(){
    $('html, body').animate({ scrollTop: 0 }, 100);
  })
</script>

app/views/player/main_area.html.erb
<% content_for :user_header_title do %>
  <%= image_tag 'icons/bird-blue.svg' %>
  Connect
<% end %>

<% if @user.has_role? :artist %>
  <%= render 'users/artist_header' %>
<% else %>
  <%= render 'users/user_header' %>
<% end %>

<div class="row">
  <div class="col-lg-3">
    <%= render 'player/player_page_menu' %>
  </div>

  <div class="col-lg-9 music-wrapper">
    <div class="music-block player-main-area" style="padding-top: 280px;">
      <% if @main_area %>
      <a href="<%= @main_area[:link] %>" class="banner">
        <%= image_tag @main_area[:img], class: "banner-img" %>
      </a>
      <% else %>
        <% release = ReleasePresenter.new(Release.published.first, current_user) %>
        <div class="banner">
          <%= image_tag release.avatar.url, class: "banner-img" %>

          <%= link_to '', "#",
                      data: { 
                        source_type: 'release', 
                        source_id: release.id,
                        virtual: true
                      }, 
                      class: "play-release-#{release.id} playlist-play-playlist",
                      remote: true %>

          <div class="banner-footer">
            <div class="time"><%= time_ago_in_words( release.release_date ).upcase %> AGO</div>

            <div class="left-side">
              <div class="banner-title">
                <%= release.title %>
                <span class="tracks-count"><%= "#{release.tracks.count} #{'track'.pluralize(release.tracks.count)}" %></span>
                <div class="release-artists">
                  By <%= release.artists(2) %>
                </div>
              </div>
              
              <%#= release.average('main').try(:avg).try(:round,1) %>
              <%= rating_for release, 'main', 
                  star: 4, 
                  cancel: false,
                  readonly: true,
                  star_on: image_path('rate/egg/star-on.svg'), 
                  star_half: image_path('rate/egg/star-on.svg'), 
                  star_off: image_path('rate/egg/star-off.svg')
                %>
            </div>

            <%= link_to 'Details', release, class: 'details' %>
          </div>
        </div>
      <% end %>

      <div class="main-area-nav mb-3">
        <div class="row h-100">
          <div class="col-md-4 d-flex align-items-center justify-content-center">
            <%= link_to artists_path do %>
              <%= image_tag 'dirtybird-bbq-stage.png', class: 'main-area-nav-bgrd' %>
              <span class="main-area-nav-caption">Artists</span>
            <% end %>
          </div>

          <div class="col-md-4 d-flex align-items-center justify-content-center">
            <%= link_to leaderboard_path do %>
              <%= image_tag 'dirtybird_bbq.png', class: 'main-area-nav-bgrd' %>
              <span class="main-area-nav-caption">Community</span>
            <% end %>
          </div>

          <div class="col-md-4 d-flex align-items-center justify-content-center">
            <%= link_to friends_path(current_user) do %>
              <%= image_tag 'JLB.png', class: 'main-area-nav-bgrd' %>
              <span class="main-area-nav-caption">Friends</span>
            <% end %>
          </div>
        </div>
      </div>

      <h2>Latest Artists</h2>
      <%= link_to 'All Artists', artists_path, class: 'see-all' %>
      <hr class="mt-1">

      <div class="row">
        <% User.with_role(:artist).order(created_at: :desc).limit(4).each do |user| %>
          <div class="col-md-6 mb-3">
            <%= render 'users/artist_gray', object: user %>
          </div>
        <% end %>
      </div>

      <h2 class="mt-4">Latest Birds</h2>
      <%= link_to 'All Members', leaderboard_path, class: 'see-all' %>
      <hr class="mt-1">

      <div class="row mb-4">
        <% User.where("users.id NOT IN (?)", 
           User.with_role(:artist)
               .pluck(:id))
               .order(created_at: :desc)
               .limit(4).each do |user| %>
          <div class="col-md-6 mb-3">
            <%= render 'users/user_gray', object: user %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/player/releases.html.erb
<% content_for :user_header_title, 'Releases' %>

<% if @user.has_role? :artist %>
  <%= render 'users/artist_header' %>
<% else %>
  <%= render 'users/user_header' %>
<% end %>

<div class="row">
  <div class="col-lg-3">
    <%= render 'player/player_page_menu' %>
  </div>

  <div class="col-lg-9 music-wrapper">
    <div class="music-block">
      <div class="row mt-3 releases-list">
        <% for release in @releases %>
          <div class="col-lg-4 col-md-6 mb-5">
            <%= render(release) %>
          </div>
        <% end %>
      </div>
      
      <div class="text-center">
        <% if @limit <= @releases.count %>
          <% _params = { player: true, user_id: @user.id } %>

          <% if params[:filters].present? %>
            <%  _params.merge!({ filters: params[:filters].permit! }) %>
          <% end %>

          <%  _params.merge!({
                page: (params[:page] ? params[:page].to_i + 1 : 2)
              }) %>

          <%= link_to "Show more", load_more_releases_path(_params), 
              remote: true, class: "btn c-btn-blue show-more" %>
        <% end %>
      </div>
    </div>
  </div>
</div>