config/routes.rb
Rails.application.routes.draw do
  mount Shrine.presign_endpoint(:store) => "/presign"

  devise_for :users, path: 'usr', controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  devise_scope :user do
    get 'usr/edit_profile', :to => 'users/registrations#edit_profile'
    put 'usr/update_profile', :to => 'users/registrations#update_profile'
    get 'usr/edit_account', :to => 'users/registrations#edit_account'
    put 'usr/update_account', :to => 'users/registrations#update_account'
  end

  resources :users, only: [:show, :index, :update] do
    collection do
      post "change_avatar"
    end
  end
  get 'load_more_leaders', to: 'users#load_more'
  get 'load_more_artists', to: 'users#load_more_artists'

  post '/rate' => 'rater#create', :as => 'rate'
  get "leaderboard", to: "users#leaderboard"
  get "choose_profile", to: "users#choose_profile"
  get "get_more_credits", to: "users#get_more_credits"
  get "success_signup", to: "users#success_signup"
  get "terms_and_conduct", to: "users#terms_and_conduct"
  delete "cancel_subscription", to: "users#cancel_subscription"
  post "apply_promocode", to: "users#apply_promocode"
  get "home", to: "users#home"
  get "final_cancellation", to: "home#final_cancellation"

  post "report", to: "home#report"

  # user profile settings urls
  get "usr/rewards", to: 'user_profile_settings#rewards'
  get "usr/egg_credits", to: 'user_profile_settings#egg_credits'
  get "usr/headers", to: 'user_profile_settings#headers'
  get "usr/skins", to: 'user_profile_settings#skins'
  get "usr/downloads", to: 'user_profile_settings#downloads'
  get "usr/billing_order_history", to: 'user_profile_settings#billing_order_history'
  get "usr/friends", to: 'user_profile_settings#friends'
  get "usr/artists", to: 'user_profile_settings#artists'
  get "usr/releases", to: 'user_profile_settings#releases'
  get "usr/chirp_feeds", to: 'user_profile_settings#chirp_feeds'
  get "usr/notifications", to: 'user_profile_settings#notifications'
  get "usr/cancel_account", to: 'user_profile_settings#cancel_account'
  put "usr/update_notification_settings", to: 'user_profile_settings#update_notification_settings', :as => 'update_notification_settings'
  put "usr/update_user_header", to: 'user_profile_settings#update_user_header', :as => 'update_user_header'
  delete "usr/cancel_account", to: 'user_profile_settings#cancel_account_perform'

  get "get_feed_token", to: "feeds#get_feed_token"
  get "add_feed_item", to: "feeds#add_feed_item"
  get "add_notify_item", to: "feeds#add_notify_item"
  get "load_more_feed", to: "feeds#load_more"
  get "is_seen", to: "feeds#is_seen"
  get "is_read", to: "feeds#is_read"

  get "chirp_feed", to: "users#chirp_feed"
  get "release_feed", to: "users#release_feed"
  get "artists_feed", to: "users#artists_feed"
  get "friends_feed", to: "users#friends_feed"
  get "announcement_feed", to: "users#announcement_feed"
  get "interviews_feed/:id", to: "users#interviews_feed", as: "interviews_feed"
  get "videos_feed/:id", to: "users#videos_feed", as: "videos_feed"
  get "others_feed/:id", to: "users#others_feed", as: "others_feed"
  get "friends/:id", to: "users#friends", as: "friends"
  get "idols/:id", to: "users#idols", as: "idols"

  ActiveAdmin.routes(self)

  devise_scope :user do
    authenticated do
      root 'users#home', as: :authenticated_root
    end
  end

  get 'admins/:id', to: 'users#admin', as: 'admin'
  get 'artists/:id', to: 'users#artist', as: 'artist'
  get 'artist_releases/:id', to: 'users#artist_releases', as: 'artist_releases'
  get 'artist_tracks/:id', to: 'users#artist_tracks', as: 'artist_tracks'
  get 'artists', to: 'users#artists'
  get 'badges/:id', to: 'users#badges', as: 'badges'

  get 'about', to: 'home#about'
  get 'birdfeed', to: 'home#birdfeed'
  post 'share', to: 'home#share'
  get 'badge-notify', to: 'home#badge_notify'
  get 'pricing', to: 'home#pricing'
  get 'information', to: 'home#information'
  get 'how_eggs_work', to: 'home#how_eggs_work'

  resources :contacts, only: [:index, :create]
  resources :slider_images

  resources :announcements, only: [:show]
  resources :releases, only: [:show, :index]
  get '/releases/:id/download', to: 'releases#download', as: :release_download
  get '/tracks/:id/download', to: 'tracks#download', as: :track_download
  get "search_releases", to: "releases#search"
  get "fill_track_title", to: "tracks#fill_track_title"
  get 'load_more_releases', to: 'releases#load_more'

  resources :tracks
  get 'track_listened', to: 'tracks#track_listened'
  get 'track_listened_for_review', to: 'tracks#track_listened_for_review'
  get 'tracks_play', to: 'tracks#play'
  get 'tracks_list', to: 'tracks#list'
  get 'track_clicked', to: 'tracks#track_clicked'

  resources :player do
    get 'liked_playlists'
    get 'liked_tracks'
    get 'recently_tracks'
    get 'downloaded_tracks'
    get 'favorites'
    get 'connect'
    get 'listen'
    get 'artists'
    get 'fans'
    get 'playlists'
    get 'badges'
  end
  get 'player_load_more_leaders', to: 'player#load_more_fans'
  get 'player_load_more_artists', to: 'player#load_more_artists'

  resources :playlists
  get 'playlist_load', to: "playlists#load"
  post "sync_playlist", to: "playlists#sync_playlist"

  namespace :callbacks do
    post 'transloadit', to: 'transloadit#create'
    post 'braintree/nonce', to: 'braintree#nonce'
    # post 'braintree/analytics_notify', to: 'braintree#analytics_notify'
  end


  resources :topics
  resources :posts

  resources :follows
  get '/accept_request/:user_id/', to: 'follows#accept_request', as: :accept_request
  get '/reject_request/:user_id/', to: 'follows#reject_request', as: :reject_request
  get 'is_seen_requests', to: 'follows#is_seen_requests'


  resources :comments
  get 'comment_reply_form', to: 'comments#reply_form'

  resources :likes

  resources :chirp, controller: 'topic_categories', only: [:show, :index] do
    # get 'category/:id', to: "topics#category"
    resources :topics
    # get 'pin'
    # get 'unpin'
    # get 'lock'
    # get 'unlock'
  end

  resources :notifications

  root "home#index"

  mount Shrine.presign_endpoint(:store) => "/presign"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include UsersHelper
  include StreamRails::Activity

  before_action :authenticate_user!, 
      except: [:index, :about, :birdfeed, :share, :report, :pricing, 
          :information, :final_cancellation]
  before_action :set_notifications,
      only: [:about, :birdfeed, :pricing, :information, :how_eggs_work]

  def index
    @slider = SliderImage.all.ordered

    @leader_users = leaderboard_query('leaders', 1, 10, true)

    @artists = User.with_role(:artist)
                   .order('created_at ASC')
                   .includes(:artist_info)
                   .limit(10)

    @releases = Release.published.where(
      'published_at <= :now AND (published_at >= :user_max OR available_to_all = true)',
      now: DateTime.now,
      user_max: DateTime.now - 2.month
    ).order('published_at DESC')
    .limit(10)

    @badge_kinds = BadgeKind.visible

    #TODO decrease count of queries
    # @leader_points = {}

    # @badge_points = BadgePoint.all.freeze

    # @leader_users.each do |user|
    #   @leader_points["leader_#{user.id}"] ||= {}
    #   @badge_kinds.each do |kind|
    #     @leader_points["leader_#{user.id}"]["kind#{kind.id}"] = @badge_points.where(user_id: user.id, badge_kind_id: kind.id).pluck(:value).sum
    #   end
    # end
  end

  def about
  end

  def information
  end

  def final_cancellation
  end

  def birdfeed
    begin
      feed = StreamRails.feed_manager.get_feed('masterfeed', 1)
      results = feed.get()['results']
    rescue Faraday::Error::ConnectionFailed, Stream::StreamApiResponseException
      results = []
    end
    
    @enricher = StreamRails::Enrich.new
    @enricher.add_fields([:foreign_id])
    @activities = @enricher.enrich_activities(results)
  end

  def share
    if params[:subtype].present? && params[:subtype_id].present?
      object = "#{params[:subtype].capitalize}:#{params[:subtype_id]}"
      _object_id = params[:subtype_id]
      verb = params[:subtype].capitalize
    else
      object = "#{params[:type].capitalize}:#{params[:type_id]}"
      _object_id = params[:type_id]
      verb = params[:type].capitalize
    end

    share = Share.create(
          user_id: current_user.try(:id),
          shareable_type: verb,
          shareable_id: _object_id,
          social: params[:social]
      )

    if current_user
      feed = StreamRails.feed_manager.get_user_feed( current_user.id )
      activity = {
        actor: "User:#{current_user.id}",
        verb: verb,
        object: object,
        foreign_id: "Share",
        social: params[:social],
        time: DateTime.now.iso8601
      }

      feed.add_activity(activity)

      current_user.change_points( 'share', params[:type].capitalize )
    end

    render json: {}
  end

  def badge_notify
    return unless current_user

    badges = []

    current_user.badge_levels.each do |level|
      unless level.notified?
        badges << level.badge_id
        level.update_attributes( notified: true )
      end
    end

    render json: { badges: badges }
  end

  def report
    report = Report.create(
          user_id: current_user.try(:id),
          reportable_type: params[:type],
          reportable_id: params[:id],
          ip_address: request.remote_ip,
          text: params[:text]
      )

    report_data = report.slice(:id,:user_id,:reportable_type,:reportable_id,:text)
    report_data[:text] = report_data[:text][0..30]
    SLACK_REPORTS.ping report_data.to_s

    admins = User.with_role(:admin)

    admins.each do |user|
      next if current_user && user.id == current_user.id

      feed = StreamRails.feed_manager.get_notification_feed( user.id )

      activity = {
        actor: "User:#{current_user.try(:id)}",
        verb: "Report",
        object: "#{params[:type]}:#{params[:id]}",
        foreign_id: "Report:#{report.id}",
        time: DateTime.now.iso8601
      }

      feed.add_activity(activity)
    end

  end

  def pricing
  end

  def how_eggs_work
  end

end

app/helpers/home_helper.rb
module HomeHelper
  
  def primary_avatar name
    img = Avatarly.generate_avatar(name.parameterize, opts={size: 256})
    filepath = "public/images/#{SecureRandom.hex}.png"
    File.open(filepath, 'wb') do |f|
      f.write img
    end

    File.new filepath
  end
end

app/views/home/_report_form.html.erb
<%= form_tag report_path, remote: true, class: "w-100" do %>
  <%= label_tag "text-#{object.id}", "Text", class: "sr-only" %>
  <%= text_area_tag :text, nil, class: "form-control mb-1", id: "text-#{object.id}" %>
  <%= hidden_field_tag :type, object.class.to_s, id: "type-#{object.id}" %>
  <%= hidden_field_tag :id, object.id, id: "id-#{object.id}" %>
  <%= submit_tag "Report", class: "btn c-btn-blue" %>
<% end %>

app/views/home/about.html.erb
<h1>What Is Birdfeed?</h1>
<p>
  Birdfeed is a subscription service to DIRTYBIRD, the record label & events company and all-around awesome company.
</p>
<p>
  We want to have a direct line to our most important people on earth - you, our fans - so we can get you the music releases first, exclusive releases that you can’t find anywhere else, ticket discounts to shows (and sometimes free tickets), meet and greets with the artists and discounts off label merchandise.
</p>
<p>
  When you sign up for this service, you will be able to access 3 months worth of past releases, plus 2 back catalog releases of our choice. This service is only $6.99/9.99/month or $75.00/99.0 annually. You can quit at any time!
</p>

<% unless current_user %>
  <p>
    <%= link_to "Join The Birdfeed", new_user_registration_path, class: "btn btn-lg btn-danger" %>
  </p>
<% end %>

app/views/home/birdfeed.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="c-panel bg-white">
      <div class="c-flag mb-4">BIRDFEED</div>

      <div class="feed-block" data-masterfeed="true">
        <%= render 'feeds/masterfeed' %>
      </div>

      <div id="loading" style="display: none;">Loading...</div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="sticky-top">
      <!-- FOLLOWERS -->
      <div class="c-panel bg-white mb-4">
        <div class="c-flag c-flag-inner mb-2"></div>

        <div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/chrip.html.erb
Chrip

app/views/home/final_cancellation.html.erb
<div class="success-signup">
  <div class="success-banner">
    <div class="success-logo">
      <%= image_tag 'icons/flash.svg', class: "flash-lightning" %>
      <%= image_tag 'birdfeed-logo-white.png', class: 'success-logo-img' %>
    </div>

    <div class="text-1">
      WE WILL MISS YOU
      <%= image_tag 'icons/red-bird.svg', class: "d-inline" %>
    </div>

    <div class="text-2">
      COME BACK WHENEVER
    </div>

    <div class="success-bottom">
      WE WILL STILL BE HERE
    </div>
  </div>

  <p class="text-center mb-4 cancel-description">
    YOUR MEMBERSHIP HAS BEEN CANCELLED
  </p>

  <div class="text-center mb-4 contact-description">
    IF YOU'VE SUBMITTED THIS FORM IN ERROR PLEASE <a>CONTACT US</a> WITHIN 24 HOURS
  </div>

  <div class="text-center">
    <button class="take-btn">TAKE ME ANYWHERE BUT HERE</button>
  </div>
</div>

app/views/home/how_eggs_work.html.erb
<div class="signup-header" style="margin-bottom: -100px;">
  <%= image_tag '/images/birdfeed-header.jpg', class: "h-100" %>

  <div class="success-banner signup-logo">
    <div class="success-logo">
      <%= image_tag 'icons/flash.svg', class: "flash-lightning" %>
      <%= image_tag 'birdfeed-logo-white.png', class: 'success-logo-img' %>
    </div>

    <div class="text-1">
      HOW EGGS WORK
    </div>

    <div class="text-2">
      AND HOW TO USE THEM
    </div>

    <div class="success-bottom d-flex justify-content-around">
      <span>HUNT</span>
      <span>STACK</span>
      <span>Crack</span>
    </div>
  </div>
</div>

<div class="signup-panel c-panel bg-white">
  <div class="black-square">
    <div class="row">
      <div class="col-4 d-none d-lg-block">
        <%= image_tag 'egg-big.svg', class: "black-square-img" %>
      </div>
      <div class="col-8">
        <h3 class="h3-eggs">What are eggs?</h3>
        <p class="mb-4">
          Eggs are Birdfeeds exchange system, You can trade eggs for music downloads, Dirtybird & artist items as well as exclusive access to areas in the site and events.
        </p>
        <h3 class="h3-eggs">VIB members only</h3>
        <p class="mb-4">
          In order to particiapte in the Birdfeed egg credit system you musist hold a membership status of VIB
        </p>

        <%= link_to "Sign up", new_registration_path(resource_name), 
            class: "btn c-btn-red btn-square btn-wide" %>
        &nbsp;
        <%= link_to "Upgade", choose_profile_path, 
            class: "btn c-btn-blue btn-square btn-wide" %>
      </div>
    </div>
  </div>

  <h2 class="h2-eggs">WHAT do I Get for my Eggs?</h2>

  <div class="row mb-4 pb-4">
    <div class="col-lg-5">
      <h2 class="h2-eggs text-left text-red">Available Now</h2>
      <h3 class="h3-eggs">Music Downloads:</h3>
      <p>
        Use your egggs to download the latest releases or from the entire Dirtybird catalog of EPs LPs, remixes and exclusives all in one place. 
      </p>
      <div class="d-flex align-items-center justify-content-between">
        <%= image_tag 'usual.png' %>
        <%= image_tag 'd_select.png' %>
        <%= image_tag 'exclusive.png' %>
      </div>
    </div>

    <div class="col-lg-7">
      <div class="d-flex justify-content-between">
        <%= image_tag 'release1.jpg', width: '32%', height: '100%' %>
        <%= image_tag 'release2.jpg', width: '32%', height: '100%' %>
        <%= image_tag 'release3.jpg', width: '32%', height: '100%' %>
      </div>
    </div>
  </div>

  <div class="row mb-4 pb-4">
    <div class="col-md-6 mb-4">
      <div class="download-now-eggs">
        <div class="download-now-head">download now</div>
        <div class="d-flex justify-content-around w-100">
          <div class="download-now-pane">.WAV</div>
          <div class="download-now-pane">.mp3</div>
          <div class="download-now-pane">.aiff</div>
          <div class="download-now-pane">.Flacc</div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <h3 class="h3-eggs">The Tracks you download</h3>
      <p>
        Our track system is a one trick pony, if you use an egg for  downloading a track or releaese you own it and you can download it in .wav .mp3 .aiff .flacc as many times as you like forever. 
      </p>
    </div>
  </div>

  <hr class="mb-4 pb-4">

  <div class="row mb-4 pb-4">
    <div class="col-lg-5">
      <h2 class="h2-eggs text-left text-red">COMING SOON</h2>
      <h3 class="h3-eggs">GEAR AND MUCh MORE</h3>
      <p>
        We’ve got a growing list of pportunities for you to use your eggs, our advice, stack as many as you can so when we open up shop your ready to grab some stuff.
      </p>
      <ul class="ul-bird">
        <li>Birdfeed & Dirtybird gear</li>
        <li>Track Packs</li>
        <li>Exclusive remixes</li>
        <li>Exclusive access</li>
        <li>Stickers</li>
        <li>Dirtybird & patches </li>
        <li>Track & release stems</li>
        <li>Birdfeed site profile & status upgrades</li>
        <li>Mystery Boxes</li>
        <li>And much  more!</li>
      </ul>
    </div>

    <div class="col-lg-7">
      <div class="d-flex justify-content-between mb-4">
        <%= image_tag 'hoody.png', width: '32%', height: '100%' %>
        <%= image_tag 't-shirt.png', width: '32%', height: '100%' %>
        <%= image_tag 'stickers.png', width: '32%', height: '100%' %>
      </div>

      <div class="p-4" style="border-radius: 5px;border: 1px solid rgba(112, 112, 112, 0.54);">
        <div class="row">
          <div class="col-sm-5 mb-3">
            <%= image_tag 'bird-shop.svg', class: "w-100" %>
          </div>
          <div class="col-sm-7">
            <h3 class="h3-eggs">Birdfeed  SHOP</h3>
            <p>
              The Birdfeed shop is coming soon! and will allow all members to use their egg credits to purchase. VIB members will be given opportunities to use their egg credits please note that the Birdfeed shop opens and closes just just like any other shop. 
            </p>
            <P>
              All shop offers end at the end of every season to keep items fresh and new. 
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <hr class="mb-4 pb-4">

  <h2 class="h2-eggs">The basics of Eggs</h2>

  <div class="row mb-4 pb-4">
    <div class="col-lg-6 mb-4">
      <div class="row">
        <div class="col-sm-6 d-flex align-items-center justify-content-center">
          <%= image_tag 'eggs-shop.svg', class: 'w-75' %>
        </div>
        <div class="col-sm-6">
          <h3 class="h3-eggs">Purchase More Eggs</h3>
          <p>
            Purchasing eggs is simple you can purchse eggs in quantities of 6 pack, 13 bakers donzen or 18 big large.  You must be a participating member to purchase eggs. 
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-6 mb-4">
      <div class="row">
        <div class="col-sm-6 d-flex align-items-center justify-content-center">
          <%= image_tag 'eggs-rack.svg', class: 'w-75' %>
        </div>
        <div class="col-sm-6">
          <h3 class="h3-eggs">Stacking Eggs</h3>
          <p>
            So long as you hold an VIB membership your eggs can stack monthly they contnue to rollover, the more eggs you have the more oppotunities you have to purchase cooler stuff. 
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-6 mb-4">
      <div class="row">
        <div class="col-sm-6 d-flex align-items-center justify-content-center">
          <%= image_tag 'eggs-brolly.svg', class: 'w-75' %>
        </div>
        <div class="col-sm-6">
          <br>
          <br>
          <br>
          <br>
          <h3 class="h3-eggs">Egg DRop</h3>
          <p>
            Every month VIB members are dropped 10 freshly laid  eggs into their account to use as they please.
          </p>
        </div>
      </div>
    </div>
    <div class="col-lg-6 mb-4">
      <div class="row">
        <div class="col-sm-6 d-flex align-items-center justify-content-center">
          <%= image_tag 'egg-colored.png', class: 'w-75' %>
        </div>
        <div class="col-sm-6">
          <h3 class="h3-eggs">Designer Eggs</h3>
          <p>
            Designer Eggs are not egg credits they part of the Birdfeed game system and are hidden seasonally throughout the website. These eggs are collected by Birdfeed members and sometimes when found hold egg credits within them. Both VIB & Insiders can play to collect designer eggs. In the case that the prize inside the designer egg is egg credits only VIB members will collect ton that part of the prize.  
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="release-flag-block">
  <div class="c-flag">LATEST RELEASES</div>
  <%= link_to "SEE ALL", releases_path, class: "btn c-btn-blue" %>
</div>

<div class="h-carousel mb-4">
  <%= render @releases %>
</div>

<div class="row">
  <!-- FANS LEADERBOARD -->
  <div class="col-lg-8">
    <div class="c-panel bg-br-blue mb-4">
      <div class="c-flag mb-4" style="left: -31px;">THE BIG 10</div>
      <%= link_to "SEE ALL", users_path, class: "btn c-btn-black" %>

      <ol class="fans-block light-scroll mt-1">
        <% @leader_users.each do |u| %>
          <% user = User.find u['id'] %>
          <li style="margin-bottom: 20px;">
            <%= link_to user, class: "d-inline-block align-middle #{avatar_style(user)}" do %>
              <%= image_tag user.avatar.thumb, class: "user-avatar", alt: '' %>
            <% end %>

            <div class="fan-body">
              <div class="fan-name">
                <%= user.name.upcase %>
                <%= image_tag 'icons/point-green.svg', class: "point-green" if user.online? %>
              </div>
              <b><%= "#{user.points} POINTS" %></b>

              <div class="rating-chart">
                <div class="rating-kinds">
                  <% @badge_kinds.each do |kind| %>
                    <div><%= kind.name %></div>
                  <% end %>
                </div>

                <div class="rating-kind-points">
                  <% @badge_kinds.each do |kind| %>
                    <div><%= user.points(kind.id) %></div>
                  <% end %>
                </div>

                <div class="rating-bars">
                  <% @badge_kinds.each do |kind| %>
                    <% color = case kind.name 
                      when "music" then "red"
                      when "forum" then "blue"
                      when "community" then "yellow"
                      end %>
                    <div class="progress-wrapper">
                      <div class="progress-<%= color %>">
                        <div class="c-progress-bar" role="progressbar" style="width: <%= user.next_badges[kind.id] || 0 %>%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ol>
    </div>
  </div>

  <!-- ARTISTS -->
  <div class="col-lg-4">
    <div class="c-panel bg-c-dark mb-4" style="border: 4px solid #faae03;box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16);">
      <div class="c-flag c-flag-inner mb-4" style="left: -31px;">NEW DB ARTISTS</div>
      <%= link_to "SEE ALL", artists_path, class: "btn c-btn-blue" %>

      <ol class="users-block dark-scroll list-unstyled mt-1">
        <% @artists.each do |artist| %>
          <li>
            <%= link_to artist_path(artist), 
                class: "d-inline-block align-middle #{avatar_style(artist)}" do %>
              <%= image_tag artist.avatar.thumb,
                  class: "user-avatar artist-style",
                  alt: '' %>
            <% end %>
            <div>
              <h5>
                <%= link_to artist.name, artist_path(artist) %>
                <%= image_tag 'icons/point-green.svg', class: "point-green" if artist.online? %>
              </h5>
              <div>
                <%= artist.try(:artist_info).try(:tracks_count) || 0 %>
                <%= "Track".pluralize(artist.try(:artist_info).try(:tracks_count)) %>
                /
                <%= artist.try(:artist_info).try(:followers_count) || 0 %>
                <%= "Follower".pluralize(artist.try(:artist_info).try(:followers_count)) %>
              </div>
            </div>
          </li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/home/report.js.erb
$('.comment-controls').collapse('hide');
$('.modal').modal('hide');

  $('.notice').text('Report was sent').show();

    setTimeout(function(){
    $('.notice').fadeOut('slow');
  },3000);