config/routes.rb
Rails.application.routes.draw do
  mount Shrine.presign_endpoint(:store) => "/presign"

  devise_for :users, path: 'usr', controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }

  devise_scope :user do
    get 'usr/edit_profile', :to => 'users/registrations#edit_profile'
    put 'usr/update_profile', :to => 'users/registrations#update_profile'
    get 'usr/edit_account', :to => 'users/registrations#edit_account'
    put 'usr/update_account', :to => 'users/registrations#update_account'
  end

  resources :users, only: [:show, :index, :update] do
    collection do
      post "change_avatar"
    end
  end
  get 'load_more_leaders', to: 'users#load_more'
  get 'load_more_artists', to: 'users#load_more_artists'

  post '/rate' => 'rater#create', :as => 'rate'
  get "leaderboard", to: "users#leaderboard"
  get "choose_profile", to: "users#choose_profile"
  get "get_more_credits", to: "users#get_more_credits"
  get "success_signup", to: "users#success_signup"
  get "terms_and_conduct", to: "users#terms_and_conduct"
  delete "cancel_subscription", to: "users#cancel_subscription"
  post "apply_promocode", to: "users#apply_promocode"
  get "home", to: "users#home"
  get "final_cancellation", to: "home#final_cancellation"

  post "report", to: "home#report"

  # user profile settings urls
  get "usr/rewards", to: 'user_profile_settings#rewards'
  get "usr/egg_credits", to: 'user_profile_settings#egg_credits'
  get "usr/headers", to: 'user_profile_settings#headers'
  get "usr/skins", to: 'user_profile_settings#skins'
  get "usr/downloads", to: 'user_profile_settings#downloads'
  get "usr/billing_order_history", to: 'user_profile_settings#billing_order_history'
  get "usr/friends", to: 'user_profile_settings#friends'
  get "usr/artists", to: 'user_profile_settings#artists'
  get "usr/releases", to: 'user_profile_settings#releases'
  get "usr/chirp_feeds", to: 'user_profile_settings#chirp_feeds'
  get "usr/notifications", to: 'user_profile_settings#notifications'
  get "usr/cancel_account", to: 'user_profile_settings#cancel_account'
  put "usr/update_notification_settings", to: 'user_profile_settings#update_notification_settings', :as => 'update_notification_settings'
  put "usr/update_user_header", to: 'user_profile_settings#update_user_header', :as => 'update_user_header'
  delete "usr/cancel_account", to: 'user_profile_settings#cancel_account_perform'

  get "get_feed_token", to: "feeds#get_feed_token"
  get "add_feed_item", to: "feeds#add_feed_item"
  get "add_notify_item", to: "feeds#add_notify_item"
  get "load_more_feed", to: "feeds#load_more"
  get "is_seen", to: "feeds#is_seen"
  get "is_read", to: "feeds#is_read"

  get "chirp_feed", to: "users#chirp_feed"
  get "release_feed", to: "users#release_feed"
  get "artists_feed", to: "users#artists_feed"
  get "friends_feed", to: "users#friends_feed"
  get "announcement_feed", to: "users#announcement_feed"
  get "interviews_feed/:id", to: "users#interviews_feed", as: "interviews_feed"
  get "videos_feed/:id", to: "users#videos_feed", as: "videos_feed"
  get "others_feed/:id", to: "users#others_feed", as: "others_feed"
  get "friends/:id", to: "users#friends", as: "friends"
  get "idols/:id", to: "users#idols", as: "idols"

  ActiveAdmin.routes(self)

  devise_scope :user do
    authenticated do
      root 'users#home', as: :authenticated_root
    end
  end

  get 'admins/:id', to: 'users#admin', as: 'admin'
  get 'artists/:id', to: 'users#artist', as: 'artist'
  get 'artist_releases/:id', to: 'users#artist_releases', as: 'artist_releases'
  get 'artist_tracks/:id', to: 'users#artist_tracks', as: 'artist_tracks'
  get 'artists', to: 'users#artists'
  get 'badges/:id', to: 'users#badges', as: 'badges'

  get 'about', to: 'home#about'
  get 'birdfeed', to: 'home#birdfeed'
  post 'share', to: 'home#share'
  get 'badge-notify', to: 'home#badge_notify'
  get 'pricing', to: 'home#pricing'
  get 'information', to: 'home#information'
  get 'how_eggs_work', to: 'home#how_eggs_work'

  resources :contacts, only: [:index, :create]
  resources :slider_images

  resources :announcements, only: [:show]
  resources :releases, only: [:show, :index]
  get '/releases/:id/download', to: 'releases#download', as: :release_download
  get '/tracks/:id/download', to: 'tracks#download', as: :track_download
  get "search_releases", to: "releases#search"
  get "fill_track_title", to: "tracks#fill_track_title"
  get 'load_more_releases', to: 'releases#load_more'

  resources :tracks
  get 'track_listened', to: 'tracks#track_listened'
  get 'track_listened_for_review', to: 'tracks#track_listened_for_review'
  get 'tracks_play', to: 'tracks#play'
  get 'tracks_list', to: 'tracks#list'
  get 'track_clicked', to: 'tracks#track_clicked'

  resources :player do
    get 'liked_playlists'
    get 'liked_tracks'
    get 'recently_tracks'
    get 'downloaded_tracks'
    get 'favorites'
    get 'connect'
    get 'listen'
    get 'artists'
    get 'fans'
    get 'playlists'
    get 'badges'
  end
  get 'player_load_more_leaders', to: 'player#load_more_fans'
  get 'player_load_more_artists', to: 'player#load_more_artists'

  resources :playlists
  get 'playlist_load', to: "playlists#load"
  post "sync_playlist", to: "playlists#sync_playlist"

  namespace :callbacks do
    post 'transloadit', to: 'transloadit#create'
    post 'braintree/nonce', to: 'braintree#nonce'
    # post 'braintree/analytics_notify', to: 'braintree#analytics_notify'
  end


  resources :topics
  resources :posts

  resources :follows
  get '/accept_request/:user_id/', to: 'follows#accept_request', as: :accept_request
  get '/reject_request/:user_id/', to: 'follows#reject_request', as: :reject_request
  get 'is_seen_requests', to: 'follows#is_seen_requests'


  resources :comments
  get 'comment_reply_form', to: 'comments#reply_form'

  resources :likes

  resources :chirp, controller: 'topic_categories', only: [:show, :index] do
    # get 'category/:id', to: "topics#category"
    resources :topics
    # get 'pin'
    # get 'unpin'
    # get 'lock'
    # get 'unlock'
  end

  resources :notifications

  root "home#index"

  mount Shrine.presign_endpoint(:store) => "/presign"
end

app/controllers/user_profile_settings_controller.rb
class UserProfileSettingsController < ApplicationController
  include UsersHelper
  include ReleasesHelper
  
  before_action :authenticate_user!
  before_action :set_notifications, only: [:rewards, :egg_credits, :headers, :skins, :downloads, :billing_order_history, :friends, :artists, :releases, :chirp_feeds, :notifications, :cancel_account, :cancel_account_perform]
  before_action :set_user
	def rewards
	end	

	def egg_credits 
	end

	def headers
    @headers = Header.all
	end

	def skins
	end

	def downloads
		@downloads = current_user.downloads
	end

	def billing_order_history
    @billing_order_histories = Braintree::Transaction.search do |search|
      search.customer_id.is current_user.braintree_customer_id
    end
	end

	def friends
	    _friends = current_user.followed_users.where("users.id NOT IN (?)", User.with_role(:artist).pluck(:id))
	    @friends = []
	    _friends.map do |friend|
	    	friend_json = JSON.parse(friend.to_json)
	    	sub_friends = friend.followed_users.where("users.id NOT IN (?)", User.with_role(:artist).pluck(:id))
	    	@friends.push({
	    		info: friend,
	    		number_of_friends: sub_friends.length
	    	})
	    end
	    @friends
	end

	def artists
	    @artists = current_user.followed_users.with_role(:artist)
	end

	def releases
		release_follows = current_user.follows.where(followable_type: "Release")		
		@releases = []
		release_follows.each do |follow|
			release = Release.find(follow.followable_id)
			@releases.push release
		end
		@releases
	end

	def chirp_feeds
		release_follows = current_user.follows.where(followable_type: "Topic")		
		@topics = []
		release_follows.each do |follow|
			topic = Topic.find(follow.followable_id)
			@topics.push topic
		end
		@topics
	end

	def notifications
    if !current_user.notification
      @notification_settings = Notification.create(user_id: current_user.id)
    else
  		@notification_settings = current_user.notification
    end
	end

  def update_notification_settings
    @notification = Notification.find(notification_params[:id])
    if @notification.update notification_params
      redirect_to root_path
    else
      redirect_to 'notifications'
    end
  end

  def update_user_header
    @header = Header.find(params[:header][:id])
    if current_user.update(header_id: params[:header][:id])
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def cancel_account

  end

  def cancel_account_perform
    if params[:submit_source] == "CANCEL MY MEMBERSHIP LEVEL"
      current_user.cancel_braintree_subscription

      flash[:notice] = 'Subscription was canceled'
      if create_cancellation
        Devise.sign_out_all_scopes ? sign_out : sign_out(:user)
        redirect_to final_cancellation_path
      else
        redirect_to usr_cancel_account_path
      end
    else
      current_user.soft_delete
      if create_cancellation
        Devise.sign_out_all_scopes ? sign_out : sign_out(:user)
        yield current_user if block_given?
        redirect_to final_cancellation_path
      else
        redirect_to usr_cancel_account_path
      end
    end
  end

private
	def set_user
		@user = current_user
	end

  def notification_params
    params.require(:notification).permit(:id, :sound_main, :desktop_main, :email_important, :email_newsletter, :email_gaming, :social_profile_new_friend_alert, :social_profile_new_friend_email, :social_profile_new_favorite_alert, :social_profile_new_favorite_email, :social_feeds_comment_alert, :social_feeds_comment_email, :social_feeds_reply_alert, :social_feeds_reply_email, :social_feeds_follow_alert, :social_feeds_follow_email, :social_friends_new_alert, :social_friends_new_email, :social_friends_comment_alert, :social_friends_comment_email, :social_friends_follow_alert, :social_friends_follow_email, :social_playlists_new_alert, :social_playlists_new_email)
  end

  def cancellation_params
    params.permit(:why_cancel_account, :your_thoughts)
  end

  def create_cancellation
      current_user.cancellations.create(cancellation_params)    
  end
end

app/views/user_profile_settings/_header.html.erb
<% if current_user.has_role? :artist %>
  <%= render 'users/artist_header' %>
<% else %>
  <%= render 'users/user_header' %>
<% end %>

app/views/user_profile_settings/artists.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'FRIENDS'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-6">
          <label class="title">
            YOUR ARTISTS
          </label>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'FRIENDS', usr_friends_path, class: 'header-btn friends-link-btn' %>
          <%= link_to 'ARTISTS', usr_artists_path, class: 'header-btn artists-link-btn' %>
        </div>
      </div>
      <div class="row page-content artists-content">
        <% @artists.each_with_index do |artist, index| %>
        	<div class="col-sm-6">
            <div class="artist">
              <div class="row custom-vertical-align">
                <div class="col-sm-4">
                  <%= image_tag artist.avatar.thumb, class: "" %>
                </div>
                <div class="col-sm-4 p-0">
                  <div class="name">
                    CLAUDE VONSTROKE
                  </div>
                  <div class="count">
                    <%= artist.artist_info.followers_count %> Followers
                  </div>
                  <div class="count">
                    ? Releases | <%= artist.artist_info.tracks_count %> Tracks
                  </div>
                </div>
                <div class="col-sm-4">
                  <button class="following-btn">
                    FOLLOWING
                  </button>
                </div>
              </div>
            </div>
        	</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_profile_settings/billing_order_history.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'BILLING'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-12">
          <label class="title">
            BILLING & ORDER HISTORY
          </label>
        </div>
      </div>
      <div class="row page-content downloads-content">
        <div class="col-sm-12">
          <table class="downloads-table">
            <tr>
              <th>
                Order ID
              </th>
              <th>
                Transaction Date
              </th>
              <th>
                Product
              </th>
              <th>
                Amount
              </th>
              <th>
                
              </th>
            </tr>
            <% @billing_order_histories.each_with_index do |history, index| %>
              <tr class="<%= index.even? ? "grey" : "dark-grey" %>">
                <td>
                  <%= history.id %>
                </td>
                <td>
                  <%= history.created_at.strftime("%m/%d/%Y")[0..-5] + history.created_at.strftime("%m/%d/%Y")[-2..-1] %>
                </td>
                <td>
                  <%= history.type %>
                </td>
                <td>
                  <%= history.amount %>
                </td>
                <td>
                  <button class="invoice-btn">
                    INVOICE
                  </button>
                </td>
              </tr>
            <% end %>
          </table>
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_profile_settings/chirp_feeds.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'FEEDS'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-6">
          <label class="title">
            YOUR FEEDS
          </label>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'RELEASE FEEDS', usr_releases_path, class: 'header-btn releases-link-btn' %>
          <%= link_to 'CHIRP FEEDS', usr_chirp_feeds_path, class: 'header-btn chirp-feeds-link-btn' %>
        </div>
      </div>
      <div class="row page-note">
        <div class="col-sm-12">
          <b class="note-text">Note:</b>
          Unfollowing feeds within a small period of time will result in the removal of the points achieved for the inital follow 
        </div>
      </div>
      <div class="row page-content downloads-content">
          <div class="col-sm-12">
            <label class="sub-title">
              CHIRP FEEDS
            </label>
          </div>
          <div class="col-sm-12">
            <table class="downloads-table">
              <tr>
                <th>
                  Date
                </th>
                <th width="40%">
                  Title
                </th>
                <th>
                  Category
                </th>
                <th>
                </th>
              </tr>
              <% @topics.each_with_index do |topic, index| %>
                <tr class="<%= index.even? ? "grey" : "dark-grey" %>">
                  <td>
                    <%= topic.created_at.strftime("%m/%d/%Y")[0..-5] + topic.created_at.strftime("%m/%d/%Y")[-2..-1] %>
                  </td>
                  <td>
                    <%= topic.title%>
                  </td>
                  <td>
                    <%= topic.category.group.title.upcase + ' / ' + topic.category.title.upcase %>
                  </td>
                  <td>
                    <button class="unfollow-btn">
                      UNFOLLOW
                    </button>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/user_profile_settings/egg_credits.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'EGG'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-6">
          <label class="title">
            EGG CREDITS
          </label>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'EGG CREDITS', usr_egg_credits_path, class: 'header-btn egg-credits-link-btn' %>
          <%= link_to 'REWARDS', usr_rewards_path, class: 'header-btn rewards-link-btn' %>
        </div>
      </div>
      <div class="row page-content egg-credits-content">
      	<div class="col-sm-3">
      		<div class="row">
            <div class="col-sm-12">
              <div class="eggs-status">
                <div class="current-eggs-status">
                  YOU HAVE <span class="number-of-eggs"> <%= @credits %> </span> EGGS AVAILABLE
                </div>
                <% if current_user && 
                      current_user.braintree_subscription_expires_at &&
                     (current_user.subscription_length == 'monthly_old' ||
                      current_user.subscription_length == 'yearly_old') %>
                  <div class="future-eggs-status">
                    <b>Your next 10 egg drop is on:</b>
                    <%= current_user.braintree_subscription_expires_at.strftime("%m/%d/%Y") %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <button class="grab-more-eggs-btn">
                GRAB MORE EGGS
              </button>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <button class="birdfeed-shop-btn">
                <%= image_tag "closed_btn.png", class: 'closed-btn' %>
                BIRDFEED SHOP
                <%= image_tag "question_mark.png", class: 'question-mark' %>
              </button>
            </div>
          </div>
      	</div>
        <div class="col-sm-9">
          <div class="eggs-collection-wrapper">
            <div class="row">
              <% group = @credits / 5 %>
              <% rest = @credits % 5 %>
              <% if group > 1 %>
                <% (1..group).each do |index| %>
                  <div class="col-sm-4">
                    <div class="w-100 eggs-collection">
                      <%= image_tag "egg.png", class: 'single-egg' %>
                      <%= image_tag "egg.png", class: 'single-egg' %>
                      <%= image_tag "egg.png", class: 'single-egg' %>
                      <%= image_tag "egg.png", class: 'single-egg' %>
                      <%= image_tag "egg.png", class: 'single-egg' %>
                      <%= image_tag "egg.png", class: 'single-egg' %>
                    </div>
                    <div class="w-100 eggs-table">
                      <%= image_tag "egg-table.png", class: 'eggs-table-img' %>
                    </div>
                  </div>                
                <% end %>
              <% end %>
              <% if rest > 0 %>
                <div class="col-sm-4">
                  <div class="w-100 eggs-collection">
                    <% (1..rest).each do |index| %>
                      <%= image_tag "egg.png", class: 'single-egg' %>
                    <% end %>
                  </div>
                  <div class="w-100 eggs-table">
                    <%= image_tag "egg-table.png", class: 'eggs-table-img' %>
                  </div>
                </div>                
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_profile_settings/friends.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'FRIENDS'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-6">
          <label class="title">
            YOUR FRIENDS
          </label>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'FRIENDS', usr_friends_path, class: 'header-btn friends-link-btn' %>
          <%= link_to 'ARTISTS', usr_artists_path, class: 'header-btn artists-link-btn' %>
        </div>
      </div>
      <div class="row page-content artists-content">
        <% @friends.each_with_index do |friend, index| %>
          <div class="col-sm-6">
            <div class="artist">
              <div class="row custom-vertical-align">
                <div class="col-sm-4">
                  <%= image_tag friend[:info].avatar.thumb, class: "" %>
                </div>
                <div class="col-sm-4 p-0">
                  <div class="name">
                    <%= friend[:info].name %>
                  </div>
                  <div class="count">
                    <%= friend[:number_of_friends] %> Friends
                  </div>
                  <div class="count">
                    <!-- <%= friend[:info].address_street.to_s + " " + friend[:info].address_street_number.to_s%> -->
                    Fam Status #1235
                  </div>
                </div>
                <div class="col-sm-4">
                  <button class="following-btn">
                    FRIENDS
                  </button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_profile_settings/headers.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'HEADERS'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-6">
          <label class="title">
            HEADERS
          </label>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'HEADERS', usr_headers_path, class: 'header-btn headers-link-btn' %>
          <%= link_to 'SKINS', usr_skins_path, class: 'header-btn skins-link-btn' %>
        </div>
      </div>
      <div class="row page-content headers-skins-content">
        <div class="col-sm-12">
          <div class="row">
            <div class="col-sm-12">
              <div class="total-numbers">2018 | <span class="real-num">6/12</span> GIFTED OR ARCHIEVED</div>
            </div>
          </div>
          <div class="row">
            <% @headers.each do |header| %>
              <div class="col-sm-6">
                <%=form_for header, url: update_user_header_path, html: {method: 'put'} do |f| %>
                  <%= f.hidden_field :id %>
                  <label class="header-label"><%= header.description %>  </label>
                  <div class="header-content">
                    <%= image_tag header.url, class: 'header-img' %>
                    <% if current_user.header_id == header.id %>
                      <button class="current">
                        CURRENT HEADER
                      </button>
                    <% else %>
                      <%= f.submit "APPLY HEADER", class:"apply" %>
                    <% end %>
                  </div>
                <% end %>
              </div>
            <% end %>
<!--             <div class="col-sm-6">
              <label class="header-label">VIB Header   </label>
              <div class="header-content">
                <%= image_tag 'user_profile_settings/header_2.png'%>
                <button class="apply">
                  APPLY HEADER
                </button>
              </div>
            </div>
            <div class="col-sm-6">
              <label class="header-label">Claude Vonstroke Gift header  </label>
              <div class="header-content">
                <%= image_tag 'user_profile_settings/header_3.png'%>
                <button class="apply">
                  APPLY HEADER
                </button>
              </div>
            </div>
            <div class="col-sm-6">
              <label class="header-label">Claude Vonstroke Gift header  </label>
              <div class="header-content">
                <%= image_tag 'user_profile_settings/header_4.png'%>
                <button class="apply">
                  APPLY HEADER
                </button>
              </div>
            </div>
            <div class="col-sm-6">
              <label class="header-label">Dirtybird BBQ Oakland Header  </label>
              <div class="header-content">
                <%= image_tag 'user_profile_settings/header_5.png'%>
                <button class="apply">
                  APPLY HEADER
                </button>
              </div>
            </div>
            <div class="col-sm-6">
              <label class="header-label">Dirtybird Campout VIB Header  </label>
              <div class="header-content">
                <%= image_tag 'user_profile_settings/header_6.png'%>
                <button class="apply">
                  APPLY HEADER
                </button>
              </div>
            </div> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user_profile_settings/releases.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'FEEDS'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-6">
          <label class="title">
            YOUR FEEDS
          </label>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'RELEASE FEEDS', usr_releases_path, class: 'header-btn releases-link-btn' %>
          <%= link_to 'CHIRP FEEDS', usr_chirp_feeds_path, class: 'header-btn chirp-feeds-link-btn' %>
        </div>
      </div>
      <div class="row page-note">
        <div class="col-sm-12">
          <b class="note-text">Note:</b>
          Unfollowing feeds within a small period of time will result in the removal of the points achieved for the inital follow 
        </div>
      </div>
      <div class="row page-content downloads-content">
          <div class="col-sm-12">
            <label class="sub-title">
              RELEASE FEEDS
            </label>
          </div>
          <div class="col-sm-12">
            <table class="downloads-table">
              <tr>
                <th>
                  Date
                </th>
                <th width="40%">
                  Title
                </th>
                <th>
                  Category
                </th>
                <th>
                </th>
              </tr>
              <% @releases.each_with_index do |release, index| %>
                <tr class="<%= index.even? ? "grey" : "dark-grey" %>">
                  <td>
                    <%= release.created_at.strftime("%m/%d/%Y")[0..-5] + release.created_at.strftime("%m/%d/%Y")[-2..-1] %>
                  </td>
                  <td>
                    <%= release.title%>
                  </td>
                  <td>
                    <%= release.catalog %>
                  </td>
                  <td>
                    <button class="unfollow-btn">
                      UNFOLLOW
                    </button>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/user_profile_settings/rewards.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'EGG'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-6">
          <label class="title">
            REWARDS
          </label>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'EGG CREDITS', usr_egg_credits_path, class: 'header-btn egg-credits-link-btn' %>
          <%= link_to 'REWARDS', usr_rewards_path, class: 'header-btn rewards-link-btn' %>
        </div>
      </div>
      <div class="row page-content rewards-content">
      	<div class="col-sm-12">
      		<p>YOU HAVE RECEIVED NO REWARDS AT THIS TIME</p>
      	</div>
      </div>
    </div>
  </div>
</div>

app/views/user_profile_settings/skins.html.erb
<%= render 'user_profile_settings/header' %>

<div class="user-profile-settings">
  <div class="row">
    <div class="side-bar col-lg-3">
      <%= render partial: 'users/user_profile_nav', locals: {current_index: 'HEADERS'}  %>
    </div>
    <div class="main-content col-lg-9">
      <div class="row page-header">
        <div class="col-sm-6">
          <label class="title">
            SKINS
          </label>
        </div>
        <div class="col-sm-6 text-right">
          <%= link_to 'HEADERS', usr_headers_path, class: 'header-btn headers-link-btn' %>
          <%= link_to 'SKINS', usr_skins_path, class: 'header-btn skins-link-btn' %>
        </div>
      </div>
      <div class="row page-content headers-skins-content">
      	<div class="col-sm-12">
      		<div class="total-numbers">2018 | <span class="real-num">1/1</span> GIFTED OR ARCHIEVED</div>
          <div class="default-grey-skin">
            <label>Default Gray</label>
            <div class="shape">
              <button class="selected-status">
                Selected
              </button>              
            </div>
          </div>
      	</div>
      </div>
    </div>
  </div>
</div>